version: '3'

services:
    api:
        image: api
        ports:
            - 8080
        environment:
            - SERVICE_PORTS=8080
        deploy:
            replicas: 3
            update_config:
                parallelism: 5
                delay: 10s
            restart_policy:
                condition: on-failure
                max_attempts: 3
                window: 120s
        networks:
            - trandung

    proxy:
        image: dockercloud/haproxy
        depends_on:
            - api
        environment:
            - BALANCE=leastconn
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 3000:80
        networks:
            - trandung
        deploy:
            placement:
                constraints: [node.role == manager]

networks:
    trandung:
        driver: overlay
